# Generated by Django 3.0.3 on 2020-03-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_favoriteblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteblog',
            options={'verbose_name_plural': 'Favorilere Eklenen Gönderiler'},
        ),
    ]
