# Generated by Django 2.2 on 2020-04-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_remove_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='bio'),
        ),
    ]
