# Generated by Django 3.0.7 on 2020-07-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20200712_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categor4',
            new_name='category4',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categor5',
            new_name='category5',
        ),
    ]
