# Generated by Django 2.2.12 on 2020-08-11 11:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20200712_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Proje Resminizi Seçiniz'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Proje Resminizi Seçiniz'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Proje Resminizi Seçiniz'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Category', verbose_name='Proje Kategorisini Seçiniz'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Category2', verbose_name='Proje Kategorisini Seçiniz'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Category3', verbose_name='Proje Kategorisini Seçiniz'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Projenizi Tanıtın'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Proje Resminizi Seçiniz'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Proje Başlığınızı Giriniz'),
        ),
    ]
