# Generated by Django 2.2.12 on 2020-08-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20200811_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bakiye',
            field=models.IntegerField(default=0, verbose_name='bakiye'),
            preserve_default=False,
        ),
    ]
