# Generated by Django 2.2.12 on 2020-08-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_auto_20200811_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bakiye',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='bakiye'),
        ),
    ]
