# Generated by Django 3.0.7 on 2020-06-26 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fallowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallowed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fallowing', to=settings.AUTH_USER_MODEL, verbose_name='Takip Edilen Kullanıcı')),
                ('fallower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fallower', to=settings.AUTH_USER_MODEL, verbose_name='Takip Eden Kullanıcı')),
            ],
        ),
    ]
