# Generated by Django 3.0.7 on 2020-06-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fallowing',
            options={'verbose_name_plural': 'Takipleşme Sistemi'},
        ),
    ]
