# Generated by Django 3.0.7 on 2020-06-29 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('takip', '0005_auto_20200628_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallowing',
            name='fallow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fallow', to=settings.AUTH_USER_MODEL, verbose_name='Takip Eden Kullanıcı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fallowing',
            name='fallowed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fallowing', to=settings.AUTH_USER_MODEL, verbose_name='Takip Edilen Kullanıcı'),
            preserve_default=False,
        ),
    ]
