# Generated by Django 3.0.7 on 2020-06-29 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('takip', '0006_auto_20200630_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallowing',
            name='fallowed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallowed', to=settings.AUTH_USER_MODEL, verbose_name='Takip Edilen Kullanıcı'),
        ),
    ]
