# Generated by Django 2.2.12 on 2020-08-29 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.IntegerField()),
                ('proje', models.CharField(max_length=150)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('alan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alan', to=settings.AUTH_USER_MODEL, verbose_name='Takip Edilen Kullanıcı')),
                ('veren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veren', to=settings.AUTH_USER_MODEL, verbose_name='Takip Eden Kullanıcı')),
            ],
        ),
    ]
