# Generated by Django 2.2.12 on 2020-08-30 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='alan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alan', to=settings.AUTH_USER_MODEL, verbose_name='Alan'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='veren',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veren', to=settings.AUTH_USER_MODEL, verbose_name='Veren'),
        ),
    ]
