# Generated by Django 2.2.12 on 2020-08-12 22:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gonderi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gonderiler',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gonderiler',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='gonderiler',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='gonderiler',
            name='category4',
        ),
        migrations.RemoveField(
            model_name='gonderiler',
            name='category5',
        ),
        migrations.RemoveField(
            model_name='gonderiler',
            name='title',
        ),
        migrations.AlterField(
            model_name='gonderiler',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Gönderinizi Giriniz'),
        ),
        migrations.AlterField(
            model_name='gonderiler',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Gönderinize Resim Ekleyebilirsiniz'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category2',
        ),
        migrations.DeleteModel(
            name='Category3',
        ),
        migrations.DeleteModel(
            name='Category4',
        ),
        migrations.DeleteModel(
            name='Category5',
        ),
    ]
