# Generated by Django 2.2.12 on 2020-08-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gonderi', '0002_auto_20200813_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gonderiler',
            options={'ordering': ['-date']},
        ),
    ]
