# Generated by Django 2.2.12 on 2020-08-25 21:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Haberler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('ozet', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('dislike', models.IntegerField()),
                ('like', models.IntegerField()),
                ('detail', ckeditor.fields.RichTextField()),
                ('status', models.IntegerField(choices=[(1, 'True'), (0, 'False')])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='HaberlerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('haberler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.Haberler')),
            ],
        ),
        migrations.CreateModel(
            name='guncelhaber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.Haberler')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('yorum', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('haberler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='haberler.Haberler')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
