# Generated by Django 2.2.12 on 2020-08-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0002_popilerhaber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haberler',
            options={'ordering': ['-create_at']},
        ),
    ]
