# Generated by Django 2.2.12 on 2020-08-05 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentid', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('status', models.IntegerField(choices=[(1, 'True'), (0, 'False')])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('dislike', models.IntegerField()),
                ('like', models.IntegerField()),
                ('güncelfon', models.IntegerField()),
                ('hedef', models.IntegerField()),
                ('oran', models.IntegerField()),
                ('detail', models.TextField()),
                ('seller', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'True'), (0, 'False')])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('satilan', models.IntegerField()),
                ('slug', models.SlugField(editable=False, max_length=130)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fonlamalar.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='FonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('fon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fonlamalar.Fon')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('yorum', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('fon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fonlamalar.Fon')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
