# Generated by Django 2.2.12 on 2020-08-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Yeni', 'Yeni'), ('Yetersiz Bakiye', 'Yetersiz Bakiye'), ('Onaylandı', 'Onaylandı'), ('Hazırlanıyor', 'Hazırlanıyor'), ('Teslimatta', 'Teslimatta'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi')], default='Yeni', max_length=15),
        ),
    ]
