# Generated by Django 2.2.12 on 2020-08-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakiye', '0002_auto_20200811_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='kupon',
            name='bakiye',
            field=models.IntegerField(default=1, verbose_name='Güncel Bakiyeniz'),
            preserve_default=False,
        ),
    ]
