# Generated by Django 2.2.12 on 2020-08-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakiye', '0003_kupon_bakiye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kupon',
            name='kod',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Kodunuzu Giriniz'),
        ),
    ]
