# Generated by Django 2.2.12 on 2020-08-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakiye', '0005_auto_20200811_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kupon',
            name='kod',
            field=models.TextField(max_length=120, verbose_name='Kodunuzu Giriniz'),
        ),
    ]
