# Generated by Django 2.2.12 on 2020-08-11 15:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakiye', '0008_auto_20200811_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gonderiler2',
            new_name='Kupon',
        ),
    ]
