# Generated by Django 2.2.12 on 2020-08-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakiye', '0009_auto_20200811_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kupon',
            old_name='title',
            new_name='kupon',
        ),
        migrations.RemoveField(
            model_name='kupon',
            name='content',
        ),
        migrations.RemoveField(
            model_name='kupon',
            name='image',
        ),
    ]
