# Generated by Django 2.2.12 on 2020-08-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakiye', '0010_auto_20200811_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kupon',
            name='kupon',
            field=models.CharField(max_length=120, verbose_name='Kuponunuzu Giriniz'),
        ),
    ]
