# Generated by Django 2.2.12 on 2020-08-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakiye', '0013_auto_20200829_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kupon',
            name='kupon',
            field=models.IntegerField(verbose_name='Kuponunuzu Giriniz'),
        ),
    ]
