# Generated by Django 2.2.12 on 2020-08-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kuponprice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
