# Generated by Django 2.2.12 on 2020-08-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_kuponprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kuponprice',
            field=models.IntegerField(),
        ),
    ]
